import {WorkflowGraph} from '../model/types'
export type NodeState='waiting'|'running'|'complete'|'error'|'cancelled'
export type WorkflowEvent={kind:'node';id:string;state:NodeState;error?:string}|{kind:'edge';id:string;value:unknown;valueType:string;remote?:boolean}|{kind:'variables';values:Record<string,unknown>}|{kind:'notice';message:string}
export interface WorkflowExecution {nodes:Record<string,NodeState>;edges:Record<string,{value:unknown;valueType:string;remote?:boolean}>;variables?:Record<string,unknown>;notice?:string}
export const emptyExecution=():WorkflowExecution=>({nodes:{},edges:{}})
export function executionEvent(state:WorkflowExecution,event:WorkflowEvent):WorkflowExecution{if(event.kind==='node')return{...state,nodes:{...state.nodes,[event.id]:event.state}};if(event.kind==='edge')return{...state,edges:{...state.edges,[event.id]:{value:event.value,valueType:event.valueType,remote:event.remote}}};if(event.kind==='variables')return{...state,variables:event.values};return{...state,notice:event.message}}
export const executionType=(value:unknown):string=>value===null?'Null':typeof value==='string'?'String':typeof value==='number'?'Number':typeof value==='boolean'?'Boolean':value===undefined?'Undefined':Array.isArray(value)?'Array':typeof value==='object'&&'type'in value?String(value.type):'Object'
export function executionLabel(value:unknown,type=executionType(value)):string{const text=typeof value==='string'?value:typeof value==='object'&&value&&'type'in value&&value.type==='Messages'&&'items'in value?`${Array.isArray(value.items)?value.items.length:0} 条消息`:typeof value==='object'&&value&&'type'in value&&value.type==='Image'?'图片':JSON.stringify(value)??'无值';return `${text.replace(/\s+/g,' ').slice(0,64)}${text.length>64?'…':''} · ${type}`}
export async function emitWorkflowEvent(listener:((e:WorkflowEvent)=>void|Promise<void>)|undefined,event:WorkflowEvent){if(!listener)return;try{await listener(structuredClone(event))}catch{/* Observers cannot corrupt runtime values or fail execution. */}}
export function comfyExecutionEvent(graph:WorkflowGraph,message:any,promptId:string,previous:string|null):{events:WorkflowEvent[];active:string|null}{const data=message?.data;if(!data||data.prompt_id!==promptId)return{events:[],active:previous};const events:WorkflowEvent[]=[];if(message.type==='executing'){const id=data.node==null?null:String(data.node);if(previous&&previous!==id)events.push({kind:'node',id:previous,state:'complete'});if(id&&graph.nodes.some(n=>n.id===id)){events.push({kind:'node',id,state:'running'});for(const link of graph.links.filter(l=>l.to===id)){const source=graph.nodes.find(n=>n.id===link.from);if(source?.kind==='comfy')events.push({kind:'edge',id:link.id,value:'服务端数据',valueType:source.outputs.find(p=>p.name===link.output)?.type||'Unknown',remote:true})}return{events,active:id}}return{events,active:null}}if(message.type==='execution_cached')for(const id of data.nodes||[])if(graph.nodes.some(n=>n.id===String(id)))events.push({kind:'node',id:String(id),state:'complete'});if(message.type==='execution_error'&&data.node_id)events.push({kind:'node',id:String(data.node_id),state:'error',error:data.exception_message});return{events,active:previous}}
