import assert from 'node:assert/strict'
import {test} from 'node:test'
import {createWorld} from '../src/model/templates'
import {appendViewField,bindingFields,bindingText,createInterfaceView,currentBinding,freshViewField,normalizeViews,patchFieldTree,removeInterfaceView,updateInterfaceView} from '../src/model/interfaceViews'
import {exportFiles} from '../src/model/markdown'
import {ClassDocument,Entity,World} from '../src/model/types'
const custom=():World=>{const world=createWorld('自定义');const doc:ClassDocument={id:'items',name:'物件',fileName:'物件.md',entities:[],schema:[{id:'description',keyType:'Const',key:'说明',valueType:'Content'},{id:'links',keyType:'Const',key:'关联',valueType:'Object',children:[{id:'item',keyType:'Class',classId:'items',key:'目标',valueType:'Object',repeatable:true,children:[{id:'note',keyType:'Const',key:'注释',valueType:'Text'}]}]}]};doc.entities=[{id:'a',name:'甲',fields:[{id:'a-desc',schemaId:'description',key:'说明',value:'第一行\n第二行',children:[]}]},{id:'b',name:'乙',fields:[]}];return {...world,documents:[...world.documents,doc]}}
test('legacy view migration preserves world files, stable identities and independent graph state',()=>{const world=createWorld('旧世界');const legacy={...world,views:undefined};const next=normalizeViews(legacy),graph=next.nodes.find(n=>n.viewType==='graph')!,map=next.nodes.find(n=>n.viewType==='map')!;assert.equal(next.views?.[graph.id].parentClassId,'people');assert.equal(next.views?.[map.id].parentClassId,'places');assert.deepEqual(next.documents,world.documents);assert.notEqual(next.views?.[graph.id].graph,world.graph);assert.deepEqual(normalizeViews(next),next)})
test('current schema-ID bindings and fixed concrete-ID bindings preserve different scopes and Markdown semantics',()=>{const world=custom(),view=createInterfaceView(world,'items','graph','自定义图'),entity=world.documents.find(d=>d.id==='items')!.entities[0];assert.equal(bindingText(world,view,currentBinding('member',['description']),entity),'第一行\n第二行');assert.match(bindingText(world,view,currentBinding('member',['description'],'markdown'),entity),/### 说明/);const renamed={...entity,fields:entity.fields.map(f=>({...f,key:'改名'}))};assert.equal(bindingText(world,view,currentBinding('member',['description']),renamed),'第一行\n第二行');assert.equal(bindingText(world,view,{scope:'fixed',source:'member',path:['a-desc'],classId:'items',entityId:'a',mode:'content'},world.documents.find(d=>d.id==='items')!.entities[1]),'第一行\n第二行');assert.equal(bindingText(world,view,currentBinding('member'),entity),'');assert.equal(bindingText(world,view,currentBinding('member',['deleted']),entity),'')})
test('custom nested repeated relationship objects can be inserted, projected, updated and deleted without aliasing data',()=>{const world=custom(),view=createInterfaceView(world,'items','graph','图'),doc=world.documents.find(d=>d.id==='items')!,schema=doc.schema[1].children![0],item={...freshViewField(schema),key:'[乙](物件.md#%E4%B9%99)'};const fields=appendViewField(doc.entities[0].fields,doc.schema,['links','item'],item),entity={...doc.entities[0],fields};const binding=currentBinding('member',['links','item']);assert.equal(bindingFields(world,view,binding,entity)[0].id,item.id);assert.equal(fields[0].value,'第一行\n第二行');const next=patchFieldTree(fields,item.id,{...item,value:'changed'});assert.equal(bindingFields(world,view,binding,{...entity,fields:next})[0].value,'changed');assert.equal(bindingFields(world,view,binding,{...entity,fields:patchFieldTree(next,item.id,null)}).length,0)})
test('multiple views share a parent document while configurations and layout remain independent and flat',()=>{let world=custom();const a=createInterfaceView(world,'items','graph','甲图'),b=createInterfaceView(world,'items','map','乙图');world=updateInterfaceView(updateInterfaceView(world,a),b);const edited={...a,graph:{...a.graph,positions:{a:{x:-80,y:900}}}};world=updateInterfaceView(world,edited);assert.deepEqual(world.views?.[b.id].map.positions,{});const files=exportFiles(world);assert.ok(files['物件.md']);assert.ok(files[a.fileName]);assert.ok(files[b.fileName]);assert.ok(Object.keys(files).every(key=>!/[\\/]/.test(key)));assert.equal(JSON.parse(files[a.fileName]).parentClassId,'items');const removed=removeInterfaceView(world,a.id);assert.ok(!removed.views?.[a.id]);assert.deepEqual(removed.documents,world.documents);assert.throws(()=>createInterfaceView(world,'missing','map','坏图'),/父文件类型/)})

test('reference index follows immutable document edits without stale names or deleted targets',async()=>{const {referencedEntity}=await import('../src/model/interfaceViews');const world=custom();assert.equal(referencedEntity(world,'[乙](物件.md#%E4%B9%99)')?.entity.id,'b');assert.equal(referencedEntity(world,'普通文本'),undefined);const next={...world,documents:world.documents.map(d=>d.id==='items'?{...d,entities:d.entities.map(e=>e.id==='b'?{...e,name:'新名'}:e)}:d)};assert.equal(referencedEntity(next,'[乙](物件.md#%E4%B9%99)'),undefined);assert.equal(referencedEntity(next,'[新名](物件.md#%E6%96%B0%E5%90%8D)')?.entity.id,'b');assert.equal(referencedEntity(world,'[乙](物件.md#%E4%B9%99)')?.entity.name,'乙');const deleted={...next,documents:next.documents.map(d=>d.id==='items'?{...d,entities:d.entities.filter(e=>e.id!=='b')}:d)};assert.equal(referencedEntity(deleted,'[新名](物件.md#%E6%96%B0%E5%90%8D)'),undefined)})
