import test from 'node:test'
import assert from 'node:assert/strict'
import {createAgent,workflowNode} from '../src/model/workflows'
import {typedVariableNode} from '../src/model/workflowValues'
import {newPoolVariable,editPoolVariable,reconcilePoolMemory,poolEntries} from '../src/model/variablePool'
import {runAgent} from '../src/services/workflows'
import {WorkflowEvent,executionEvent,emptyExecution,comfyExecutionEvent} from '../src/services/workflowExecution'
import {Workspace,uid} from '../src/model/types'
const ws:Workspace={worlds:[],activeWorldId:null},link=(from:string,to:string,input:string)=>({id:uid(),from,to,input,output:'value'})
test('pool identities survive rename, update every bound node and rename scoped memory',()=>{const created=newPoolVariable({},'Number'),a=typedVariableNode('Number'),b=typedVariableNode('Number');a.settings.name=b.settings.name=created.name;a.settings.variableId=b.settings.variableId=created.id;const graph={version:1 as const,nodes:[a,b],links:[]},edit=editPoolVariable(graph,created.variables,created.name,{name:'计数'});assert.equal(poolEntries(edit.variables)[0].id,created.id);assert.ok(edit.graph.nodes.every(n=>n.settings.name==='计数'));const memory=reconcilePoolMemory(created.variables,edit.variables,{one:{[created.name]:{id:created.id,type:'Number',value:12}}});assert.equal((memory!.one['计数'] as any).value,12);assert.ok(!Object.hasOwn(memory!.one,created.name));assert.throws(()=>editPoolVariable(graph,created.variables,created.name,{name:''}))})
test('pool type changes update bound ports and reset incompatible values without deleting wires',()=>{const vars={x:{id:'x',type:'String',value:'abc'}},a=typedVariableNode('String'),out=workflowNode('return');a.settings.name='x';const graph={version:1 as const,nodes:[a,out],links:[link(a.id,out.id,'value')]},edit=editPoolVariable(graph,vars,'x',{type:'Number'});assert.deepEqual(edit.variables.x,{id:'x',type:'Number',value:0});assert.equal(edit.graph.nodes[0].inputs[0].type,'NUMBER');assert.equal(edit.graph.links.length,1);assert.throws(()=>editPoolVariable(graph,vars,'x',{value:3}),/String/)})
test('runtime emits ordered execution, real wire values and cloned live variable snapshots',async()=>{const agent=createAgent(),input=workflowNode('input'),v=typedVariableNode('String'),out=workflowNode('return');v.settings.name='text';agent.graph={version:1,nodes:[input,v,out],links:[link(input.id,v.id,'value'),link(v.id,out.id,'value')]};const events:WorkflowEvent[]=[];const result=await runAgent(agent,'hello',ws,undefined,undefined,undefined,{onEvent:e=>{events.push(e);if(e.kind==='variables')(e.values as any).bad='observer cannot mutate'}});assert.equal(result.value,'hello');assert.ok(!Object.hasOwn(result.variables,'bad'));assert.equal((result.variables.text as any).value,'hello');assert.deepEqual(events.filter(e=>e.kind==='node'&&e.state==='running').map(e=>(e as any).id),[input.id,v.id,out.id]);const wires=events.filter(e=>e.kind==='edge');assert.equal(wires.length,2);assert.ok(wires.every(e=>e.kind==='edge'&&e.value==='hello'&&e.valueType==='String'));const state=events.reduce(executionEvent,emptyExecution());assert.equal(state.nodes[v.id],'complete');assert.equal(state.edges[agent.graph.links[0].id].value,'hello')})
test('failed runs expose the failing node and working values but do not commit saved memory',async()=>{const agent=createAgent(),v=typedVariableNode('Number'),divide=workflowNode('divide'),out=workflowNode('return');v.settings.name='n';v.settings['port:value']='9';divide.settings['port:b']='0';agent.variables={n:{id:'n',type:'Number',value:2}};agent.graph={version:1,nodes:[v,divide,out],links:[link(v.id,divide.id,'a'),link(divide.id,out.id,'value')]};const events:WorkflowEvent[]=[];await assert.rejects(()=>runAgent(agent,'',ws,undefined,undefined,undefined,{onEvent:e=>{events.push(e)}}),/除数/);assert.equal((agent.variables.n as any).value,2);assert.ok(events.some(e=>e.kind==='node'&&e.id===divide.id&&e.state==='error'));assert.ok(events.some(e=>e.kind==='variables'&&(e.values.n as any)?.value===9))})
test('Comfy events are scoped to the submitted prompt and label server tensors honestly',()=>{const a={...workflowNode('constant'),kind:'comfy' as const,outputs:[{name:'out0',type:'IMAGE'}]},b={...workflowNode('constant'),kind:'comfy' as const},graph={version:1 as const,nodes:[a,b],links:[{id:'wire',from:a.id,output:'out0',to:b.id,input:'images'}]};assert.equal(comfyExecutionEvent(graph,{type:'executing',data:{prompt_id:'other',node:b.id}},'p',a.id).events.length,0);const next=comfyExecutionEvent(graph,{type:'executing',data:{prompt_id:'p',node:b.id}},'p',a.id);assert.equal(next.active,b.id);assert.ok(next.events.some(e=>e.kind==='node'&&e.id===a.id&&e.state==='complete'));assert.ok(next.events.some(e=>e.kind==='edge'&&e.remote&&e.valueType==='IMAGE'&&e.value==='服务端数据'))})
