import { usePageState } from './PageSession'
import { Send, Sparkles, Square } from 'lucide-react'
import { AgentDefinition, ModelConnection, World } from '../model/types'
import ModelSelector from './ModelSelector'

export default function ChatPage({world,onChange,models,agents,onModelSettings,onSend,onStop,sending,error}:{world:World;onChange:(world:World)=>void;models:ModelConnection[];agents:AgentDefinition[];onModelSettings:()=>void;onSend:(content:string)=>void;onStop:()=>void;sending:boolean;error?:string}) {
  const [draft,setDraft]=usePageState('chat:draft','')
  const conversation=(world.chat.conversations||[]).find(item=>item.id===world.chat.activeConversationId)
  const send=()=>{const content=draft.trim();if(!content||sending)return;onSend(content);setDraft('')}
  const composer=<div className="modern-composer"><textarea value={draft} onChange={e=>setDraft(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}}} placeholder="向创作助手发送消息…" rows={2}/><div className="composer-footer"><ModelSelector models={models} value={world.chat.modelId||null} onChange={modelId=>onChange({...world,chat:{...world.chat,modelId}})} onSettings={onModelSettings}/><select className="chat-agent-select" aria-label="选择智能体" disabled={sending} value={agents.some(a=>a.id===world.chat.agent)?world.chat.agent:''} onChange={e=>onChange({...world,chat:{...world.chat,agent:e.target.value}})}><option value="">直接调用 LLM</option>{agents.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select>{sending&&<button className="send-button" title="停止等待" onClick={onStop}><Square size={14}/></button>}<button className="send-button" disabled={!draft.trim()||sending} onClick={send} title="发送"><Send size={17}/></button></div></div>
  return <div className={`chat-page ${conversation?'has-conversation':'empty-conversation'}`}>{conversation?<><header className="chat-page-header"><div><strong>{conversation.title}</strong><span>保存在当前世界</span></div></header><div className="message-scroll"><div className="message-column">{conversation.messages.map(message=><div className={`message ${message.role}`} key={message.id}>{message.role==='assistant'&&<div className="assistant-avatar"><Sparkles size={15}/></div>}<div className="message-content">{message.content}</div></div>)}</div></div><div className="chat-bottom">{composer}{error&&<p className="danger" role="alert">{error}</p>}<p>{sending?'正在生成…':'对话保存在当前世界。可以直接调用模型，或选择 Agent 工作流。'}</p></div></>:<div className="chat-welcome"><div className="chat-welcome-icon"><Sparkles size={25}/></div><h1>今天想创作什么？</h1><p>描述人物、世界或情节，从一条对话开始。</p>{composer}</div>}</div>
}
