import {Trash2} from 'lucide-react'
import {InterfaceView,World} from '../model/types'
import {bindingClass,graphRelationClass,schemaAtPath,updateInterfaceView} from '../model/interfaceViews'
import ViewBindingPicker from './ViewBindingPicker'
import GraphConfigPage from './GraphConfigPage'
export default function InterfaceConfigPage({world,view,onChange,onDelete}:{world:World;view:InterfaceView;onChange:(world:World)=>void;onDelete:()=>void}){
 const set=(next:InterfaceView)=>onChange(updateInterfaceView(world,next)),parent=world.documents.find(d=>d.id===view.parentClassId),edge=schemaAtPath(parent?.schema||[],view.bindings.edges?.path||[])
 const row=(key:string,label:string,structural=false,relative=false)=><ViewBindingPicker key={key} world={world} view={view} label={label} value={view.bindings[key]} structural={structural} emptyLabel={key==='target'?'关系对象自身':'未绑定'} schemas={relative?(edge?.children||[]):undefined} onChange={binding=>set({...view,bindings:{...view.bindings,[key]:binding}})}/>
 return <div className="page-scroll interface-config-page graph-config-page"><div className="page-heading"><div><div className="eyebrow">INTERFACE VIEW · {view.fileName}</div><h1>{view.name}配置</h1><p>以父类型实例为行，通过对象绑定投影显示元素。</p></div><div className="heading-actions"><button className="ghost danger" onClick={onDelete}><Trash2 size={16}/> 删除界面</button></div></div><div className="interface-config-body"><div className="schema-panel config-form"><label>界面名称<input value={view.name} onChange={e=>set({...view,name:e.target.value})}/></label><label>父文件类型<select value={view.parentClassId} onChange={e=>set({...view,parentClassId:e.target.value,bindings:Object.fromEntries(Object.entries(view.bindings).map(([key,b])=>[key,b.scope==='current'?{...b,path:[]}:b])),graph:{...view.graph,positions:{},lineStyles:{},domainStyles:{}},map:{...view.map,positions:{}}})}>{world.documents.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label></div><div className="schema-panel"><div className="panel-title">显示元素绑定</div>{row('title',view.kind==='graph'?'卡片名称':'地点名称')}{view.kind==='graph'?<>{row('avatar','卡片图标')}{row('subtitle','卡片副标题')}{row('domain','分组对象')}<ViewBindingPicker world={world} view={{...view,parentClassId:bindingClass(world,view,view.bindings.domain)?.id||''}} label="分组名称" value={view.bindings.domainLabel} onChange={binding=>set({...view,bindings:{...view.bindings,domainLabel:binding}})}/>{row('edges','关系集合',true)}<p className="muted">关系集合选择可重复的成员对象；以下目标与文字路径相对于每条关系对象。目标为空路径时读取该对象的 Class 键。</p>{row('target','连线目标',true,true)}{row('edgeLabel','连线文字',false,true)}{!edge&&<p className="muted">绑定关系集合后即可配置连线；未绑定时仍可查看实例卡片。</p>}</>:<>{row('description','地点说明')}{row('x','X 坐标')}{row('y','Y 坐标')}{row('image','背景图片')}<p className="muted">坐标内容应为有限数值；未绑定坐标时使用本视图的拖动位置。背景图片取父类型首个实例的绑定值。</p></>}</div>{view.kind==='graph'?<GraphConfigPage embedded relationClassId={graphRelationClass(world,view)?.id||''} domainClassId={bindingClass(world,view,view.bindings.domain)?.id||''} world={{...world,graph:view.graph}} onChange={next=>set({...view,graph:next.graph})}/>:<div className="schema-panel config-form"><label>默认背景图片<input value={view.map.image} onChange={e=>set({...view,map:{...view.map,image:e.target.value}})} placeholder="图片 URL 或 data URL"/></label><label>图例<textarea value={view.map.legend} onChange={e=>set({...view,map:{...view.map,legend:e.target.value}})}/></label></div>}</div></div>
}
