import {useRef,useState} from 'react'
import {Compass,MapPin,Minus,Plus,Scan} from 'lucide-react'
import {InterfaceView,World} from '../model/types'
import {bindingRaw,bindingText,updateInterfaceView} from '../model/interfaceViews'
import {usePageState} from './PageSession'
import {zoomAt} from '../model/graphGeometry'
export default function MapPage({world,view,onChange,onOpen}:{world:World;view:InterfaceView;onChange:(world:World)=>void;onOpen:(id:string)=>void}){
 const canvas=useRef<HTMLDivElement>(null),[pan,setPan]=usePageState('map:pan',{x:0,y:0}),[scale,setScale]=usePageState('map:scale',1),[moving,setMoving]=useState<{id?:string;x:number;y:number;origin:{x:number;y:number}}|null>(null),[selected,setSelected]=usePageState<string|null>('map:selected',null)
 const entities=world.documents.find(d=>d.id===view.parentClassId)?.entities||[]
 const position=(entity:typeof entities[number],index:number)=>{const x=bindingRaw(world,view,view.bindings.x,entity).trim(),y=bindingRaw(world,view,view.bindings.y,entity).trim();return view.map.positions[entity.id]||{x:x&&Number.isFinite(Number(x))?Number(x):180+(index%4)*220,y:y&&Number.isFinite(Number(y))?Number(y):180+Math.floor(index/4)*150}}
 const image=(bindingText(world,view,view.bindings.image,entities[0])||view.map.image).trim()
 const zoom=(factor:number,anchor?:{x:number;y:number})=>{const rect=canvas.current?.getBoundingClientRect();if(!rect)return;const next=zoomAt(pan,scale,factor,anchor||{x:rect.width/2,y:rect.height/2});setPan(next.pan);setScale(next.scale)}
 return <div className="full-map bound-map" ref={canvas} onWheel={e=>{e.preventDefault();const rect=e.currentTarget.getBoundingClientRect();zoom(e.deltaY<0?1.1:1/1.1,{x:e.clientX-rect.left,y:e.clientY-rect.top})}} onPointerDown={e=>{if(e.button!==0||(e.target as Element).closest('button,.bound-map-pin'))return;setMoving({x:e.clientX,y:e.clientY,origin:pan});e.currentTarget.setPointerCapture(e.pointerId)}} onPointerMove={e=>{if(!moving)return;const dx=e.clientX-moving.x,dy=e.clientY-moving.y;if(moving.id)onChange(updateInterfaceView(world,{...view,map:{...view.map,positions:{...view.map.positions,[moving.id]:{x:moving.origin.x+dx/scale,y:moving.origin.y+dy/scale}}}}));else setPan({x:moving.origin.x+dx,y:moving.origin.y+dy})}} onPointerUp={e=>{if(moving&&!moving.id&&Math.hypot(e.clientX-moving.x,e.clientY-moving.y)<4)setSelected(null);setMoving(null)}} onPointerCancel={()=>setMoving(null)}><div className="bound-map-transform" style={{transform:`translate(${pan.x}px,${pan.y}px) scale(${scale})`}}>{image&&<img className="bound-map-image" src={image} alt="地图背景" draggable={false}/>} {entities.map((entity,index)=>{const p=position(entity,index);return <button key={entity.id} className={`bound-map-pin ${selected===entity.id?'selected':''}`} style={{left:p.x,top:p.y}} onPointerDown={e=>{if(e.button!==0)return;e.preventDefault();e.stopPropagation();setSelected(entity.id);setMoving({id:entity.id,x:e.clientX,y:e.clientY,origin:p});canvas.current?.setPointerCapture(e.pointerId)}} onDoubleClick={()=>onOpen(entity.id)}><MapPin size={21}/><span><strong>{bindingText(world,view,view.bindings.title,entity)||entity.name}</strong><small>{bindingText(world,view,view.bindings.description,entity)}</small></span></button>})}</div><div className="map-title"><div className="eyebrow">WORLD ATLAS</div><h1>{view.name}</h1><span>{view.map.legend||'拖动地点 · 双击打开文件实例'}</span></div><div className="map-compass"><Compass size={21}/><span>N</span></div><div className="map-zoom"><button title="放大" onClick={()=>zoom(1.2)}><Plus size={17}/></button><button title="缩小" onClick={()=>zoom(1/1.2)}><Minus size={17}/></button><button title="适应屏幕" onClick={()=>{const rect=canvas.current?.getBoundingClientRect();if(!rect||!entities.length){setPan({x:0,y:0});setScale(1);return}const positions=entities.map(position),minX=Math.min(...positions.map(p=>p.x)),maxX=Math.max(...positions.map(p=>p.x))+200,minY=Math.min(...positions.map(p=>p.y)),maxY=Math.max(...positions.map(p=>p.y))+80,next=Math.min(1,(rect.width-100)/(maxX-minX),(rect.height-120)/(maxY-minY));setScale(next);setPan({x:(rect.width-(maxX-minX)*next)/2-minX*next,y:(rect.height-(maxY-minY)*next)/2-minY*next})}}><Scan size={17}/></button></div>{!entities.length&&<div className="map-notice">父文件类型尚无实例，请先添加对象。</div>}</div>
}
