import { Check, Sparkles, Trash2 } from 'lucide-react'
import { Theme, Workspace } from '../model/types'
import { activeTheme, builtinThemes, themeFields } from '../model/themes'
import ColorPicker from './ColorPicker'
export default function SettingsPage({workspace,onChange}:{workspace:Workspace;onChange:(workspace:Workspace)=>void}) {
  const theme=activeTheme(workspace),custom=!theme.builtin
  const update=(next:Theme)=>onChange({...workspace,themes:(workspace.themes||[]).map(item=>item.id===next.id?next:item)})
  return <div className="page-scroll settings-page"><div className="page-heading"><div><div className="eyebrow">APPEARANCE</div><h1>外观与主题</h1><p>选择预设色调，或新建主题并逐项调整界面颜色。</p></div></div><div className="theme-preview-grid">{[...builtinThemes,...(workspace.themes||[])].map(item=><button key={item.id} className={`theme-preview ${workspace.themeId===item.id?'selected':''}`} onClick={()=>onChange({...workspace,themeId:item.id})}><div className="theme-preview-art" style={{background:item.colors.surface,borderColor:item.colors.border}}><span style={{background:item.colors.sidebar}}/><i style={{background:item.colors.panel,borderColor:item.colors.border}}/><b style={{background:item.colors.accent}}/></div><div><strong>{item.name}</strong>{workspace.themeId===item.id&&<Check size={16}/>}</div></button>)}</div><div className="theme-editor"><div className="theme-editor-title"><div><Sparkles size={17}/><strong>{custom?'自定义颜色':'预设主题'}</strong></div>{custom&&<button className="ghost danger" onClick={()=>{const others=(workspace.themes||[]).filter(item=>item.id!==theme.id);onChange({...workspace,themes:others,themeId:'violet'})}}><Trash2 size={15}/> 删除主题</button>}</div>{custom?<><label className="theme-name">主题名称<input value={theme.name} onChange={e=>update({...theme,name:e.target.value})}/></label><div className="theme-color-grid">{themeFields.map(({key,label})=><ColorPicker key={key} label={label} value={theme.colors[key]} onChange={value=>update({...theme,colors:{...theme.colors,[key]:value}})}/>)}</div></>:<p>预设主题可直接使用。选择左侧的“新建主题”，即可从当前配色创建可编辑副本。</p>}</div></div>
}
