import TreeDisclosure from './TreeDisclosure'
import { useState } from 'react'
import { Bot, Check, Palette, Plus, Sparkles, Trash2 } from 'lucide-react'
import { Theme, Workspace, uid } from '../model/types'
import { activeTheme, builtinThemes, themeFields } from '../model/themes'
import ColorPicker from './ColorPicker'

export function SettingsSidebar({workspace,onChange,section,selectedModelId,onSection,onSelectModel}:{workspace:Workspace;onChange:(workspace:Workspace)=>void;section:'themes'|'models';selectedModelId:string|null;onSection:(section:'themes'|'models')=>void;onSelectModel:(id:string)=>void}) {
  const [modelsOpen,setModelsOpen]=useState(true),[themesOpen,setThemesOpen]=useState(true)
  const themes=[...builtinThemes,...(workspace.themes||[])]
  const create=()=>{const base=activeTheme(workspace),next:Theme={id:uid(),name:`我的主题 ${(workspace.themes||[]).length+1}`,colors:{...base.colors}};onChange({...workspace,themes:[...(workspace.themes||[]),next],themeId:next.id})}
  return <div className="settings-sidebar-content"><div className="settings-tree-parent"><button className={`settings-tree-heading ${section==='models'?'active':''}`} onClick={()=>onSection('models')} onDoubleClick={()=>setModelsOpen(!modelsOpen)}><Bot size={17}/><span>模型</span><small>{(workspace.models||[]).length}</small></button><TreeDisclosure open={modelsOpen} name="模型" onToggle={()=>setModelsOpen(!modelsOpen)}/></div>{modelsOpen&&<div className="settings-tree-branch">{(workspace.models||[]).map(model=><button key={model.id} className={`model-nav-row ${section==='models'&&selectedModelId===model.id?'active':''}`} onClick={()=>{onSection('models');onSelectModel(model.id)}}><Bot size={15}/><span>{model.name||'未命名模型'}</span>{!model.enabled&&<small>停用</small>}</button>)}{!workspace.models?.length&&<p className="settings-tree-empty">还没有接入模型</p>}</div>}<div className="settings-tree-parent"><button className={`settings-tree-heading ${section==='themes'?'active':''}`} onClick={()=>onSection('themes')} onDoubleClick={()=>setThemesOpen(!themesOpen)}><Palette size={17}/><span>主题</span></button><TreeDisclosure open={themesOpen} name="主题" onToggle={()=>setThemesOpen(!themesOpen)}/></div>{themesOpen&&<div className="settings-tree-branch">{themes.map(theme=><button className={`theme-nav-row ${workspace.themeId===theme.id?'active':''}`} key={theme.id} onClick={()=>{onSection('themes');onChange({...workspace,themeId:theme.id})}}><span className="theme-mini" style={{background:theme.colors.surface,borderColor:theme.colors.border}}><i style={{background:theme.colors.accent}}/></span><span>{theme.name}</span>{workspace.themeId===theme.id&&<Check size={15}/>}</button>)}<button className="sidebar-add" onClick={()=>{onSection('themes');create()}}><Plus size={15}/> 新建主题</button></div>}</div>
}

export default function SettingsPage({workspace,onChange}:{workspace:Workspace;onChange:(workspace:Workspace)=>void}) {
  const theme=activeTheme(workspace),custom=!theme.builtin
  const update=(next:Theme)=>onChange({...workspace,themes:(workspace.themes||[]).map(item=>item.id===next.id?next:item)})
  return <div className="page-scroll settings-page"><div className="page-heading"><div><div className="eyebrow">APPEARANCE</div><h1>外观与主题</h1><p>选择预设色调，或新建主题并逐项调整界面颜色。</p></div></div><div className="theme-preview-grid">{[...builtinThemes,...(workspace.themes||[])].map(item=><button key={item.id} className={`theme-preview ${workspace.themeId===item.id?'selected':''}`} onClick={()=>onChange({...workspace,themeId:item.id})}><div className="theme-preview-art" style={{background:item.colors.surface,borderColor:item.colors.border}}><span style={{background:item.colors.sidebar}}/><i style={{background:item.colors.panel,borderColor:item.colors.border}}/><b style={{background:item.colors.accent}}/></div><div><strong>{item.name}</strong>{workspace.themeId===item.id&&<Check size={16}/>}</div></button>)}</div><div className="theme-editor"><div className="theme-editor-title"><div><Sparkles size={17}/><strong>{custom?'自定义颜色':'预设主题'}</strong></div>{custom&&<button className="ghost danger" onClick={()=>{const others=(workspace.themes||[]).filter(item=>item.id!==theme.id);onChange({...workspace,themes:others,themeId:'violet'})}}><Trash2 size={15}/> 删除主题</button>}</div>{custom?<><label className="theme-name">主题名称<input value={theme.name} onChange={e=>update({...theme,name:e.target.value})}/></label><div className="theme-color-grid">{themeFields.map(({key,label})=><ColorPicker key={key} label={label} value={theme.colors[key]} onChange={value=>update({...theme,colors:{...theme.colors,[key]:value}})}/>)}</div></>:<p>预设主题可直接使用。选择左侧的“新建主题”，即可从当前配色创建可编辑副本。</p>}</div></div>
}
