import { Plus, Trash2, Wrench } from 'lucide-react'
import { ReactNode } from 'react'
import { ToolDefinition, Workspace, uid } from '../model/types'
import PluginFolderContents from './PluginFolderContents'

export default function ToolsPage({workspace,onChange,folderId,selected,onSelect,onFolder,folderTools}:{workspace:Workspace;onChange:(workspace:Workspace)=>void;folderId:string|null;selected:string|null;onSelect:(id:string|null)=>void;onFolder:(id:string)=>void;folderTools:ReactNode}) {
  const tools=(workspace.tools||[]).filter(item=>selected?item.id===selected:(item.folderId||null)===folderId),folder=workspace.pluginFolders?.find(item=>item.id===folderId)
  const add=()=>{const tool:ToolDefinition={id:uid(),name:'新 Tool',url:'',method:'POST',apiKey:'',bodyMode:'input',enabled:true,folderId};onChange({...workspace,tools:[...(workspace.tools||[]),tool]});onSelect(tool.id)}
  const remove=(id:string)=>{if(confirm('删除此 Tool？绑定节点会显示缺失错误。')){onChange({...workspace,tools:workspace.tools?.filter(item=>item.id!==id)});if(id===selected)onSelect(null)}}
  return <div className="model-management-page"><div className="page-heading"><div><div className="eyebrow">PLUGINS · HTTP TOOLS</div><h1>{selected?tools[0]?.name||'Tool 不存在':folder?.name||'工具'}</h1><p>配置可在 Agent Tool 节点中调用的 JSON HTTP 接口。</p></div><div className="heading-actions">{folderTools}<button className="primary" onClick={add}><Plus size={16}/> 新建 Tool</button>{selected&&<button className="ghost danger" onClick={()=>remove(selected)}><Trash2 size={15}/> 删除 Tool</button>}</div></div><div className="model-management-scroll">{!selected&&<div className="collection-grid"><PluginFolderContents workspace={workspace} section="tools" folderId={folderId} onOpen={onFolder}/></div>}{tools.map(tool=>{const patch=(value:Partial<ToolDefinition>)=>onChange({...workspace,tools:workspace.tools?.map(item=>item.id===tool.id?{...item,...value}:item)});return <section className="model-card" key={tool.id}><header><strong><Wrench size={17}/> {tool.name}</strong><button className="icon-button danger" title="删除 Tool" onClick={()=>remove(tool.id)}><Trash2 size={15}/></button></header><div className="model-form"><label>名称<input value={tool.name} onChange={e=>patch({name:e.target.value})}/></label><label>URL<input value={tool.url} onChange={e=>patch({url:e.target.value})}/></label><label>方法<select value={tool.method} onChange={e=>patch({method:e.target.value as 'GET'|'POST'})}><option>GET</option><option>POST</option></select></label><label>API Key<input type="password" value={tool.apiKey} onChange={e=>patch({apiKey:e.target.value})}/></label><label>请求体<select value={tool.bodyMode} onChange={e=>patch({bodyMode:e.target.value as 'input'|'raw'})}><option value="input">包装为 input 属性</option><option value="raw">原始输入 JSON</option></select></label><label>所属文件夹<select value={tool.folderId||''} onChange={e=>patch({folderId:e.target.value||null})}><option value="">工具根目录</option>{workspace.pluginFolders?.filter(f=>f.section==='tools').map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label></div><label className="model-enabled"><input type="checkbox" checked={tool.enabled} onChange={e=>patch({enabled:e.target.checked})}/> 启用</label></section>})}{!tools.length&&<div className="empty-card"><Wrench size={27}/><h2>添加可调用的 Tool</h2><button className="primary" onClick={add}><Plus size={16}/> 新建 Tool</button></div>}</div></div>
}
