import {useEffect,useRef,useState} from 'react'
import {ConnectionEnd,EditGraph,directedConnection,marqueeNodeIds} from '../model/graphEditing'
import useGraphEditing from './useGraphEditing'
type Point={x:number;y:number}
export default function useCanvasEditing<G extends EditGraph>(value:G,onChange:(g:G)=>void,kind:string,canvas:React.RefObject<HTMLDivElement|null>,pan:Point,scale:number,setPan:(p:Point)=>void,toggleLibrary:()=>void,connect:(edge:ReturnType<typeof directedConnection>)=>void,onError:(error:string)=>void,readOnly=false){
 const edit=useGraphEditing(value,onChange,kind),[from,setFrom]=useState<ConnectionEnd|null>(null),[cursor,setCursor]=useState<Point|null>(null),[box,setBox]=useState<{a:Point;b:Point}|null>(null)
 const live=useRef({value,edit,pan,scale,from,connect,toggleLibrary,readOnly});live.current={value,edit,pan,scale,from,connect,toggleLibrary,readOnly}
 const gesture=useRef<any>(null),portDrag=useRef<{start:Point;moved:boolean;end:ConnectionEnd}|null>(null),skipClick=useRef(false)
 const point=(p:Point)=>{const r=canvas.current!.getBoundingClientRect(),v=live.current;return{x:(p.x-r.left-v.pan.x)/v.scale,y:(p.y-r.top-v.pan.y)/v.scale}}
 const finishConnection=(a:ConnectionEnd,b:ConnectionEnd)=>{if(live.current.readOnly)return;try{live.current.connect(directedConnection(a,b));setFrom(null);onError('')}catch(e){onError(String(e))}}
 const portKey=(end:ConnectionEnd)=>kind==='flow'?`${end.id}:${end.direction==='out'?'out':end.port}`:`${end.id}:${end.direction}:${end.port}`
 const portEvents=(end:ConnectionEnd)=>({onPointerDown:(e:React.PointerEvent)=>{if(e.button!==0)return;e.stopPropagation();e.preventDefault();portDrag.current={start:{x:e.clientX,y:e.clientY},moved:false,end}},onClick:(e:React.MouseEvent)=>{e.stopPropagation();if(skipClick.current){skipClick.current=false;return}const f=live.current.from;if(f){if(portKey(f)===portKey(end))setFrom(null);else finishConnection(f,end)}else{setFrom(end);setCursor(point({x:e.clientX,y:e.clientY}))}}})
 const startNode=(e:React.PointerEvent,id:string)=>{if(e.button!==0)return;e.preventDefault();e.stopPropagation();const v=live.current;let ids=v.edit.selected;if(e.ctrlKey){ids=ids.includes(id)?ids.filter(x=>x!==id):[...ids,id];v.edit.setSelected(ids)}else if(!ids.includes(id)){ids=[id];v.edit.setSelected(ids)}v.edit.setSelectedEdges([]);skipClick.current=true;if(v.readOnly||!ids.includes(id))return;v.edit.begin();gesture.current={type:'nodes',start:point({x:e.clientX,y:e.clientY}),nodes:v.value.nodes.filter(n=>ids.includes(n.id)).map(n=>({id:n.id,x:n.x,y:n.y})),moved:false};skipClick.current=true}
 const selectNode=(e:React.MouseEvent,id:string)=>{if(skipClick.current){skipClick.current=false;return}live.current.edit.select(id,e.ctrlKey)}
 const startCanvas=(e:React.PointerEvent)=>{if(e.button!==0||(e.target as Element).closest('.flow-node,button,path'))return;e.preventDefault();const v=live.current,p=point({x:e.clientX,y:e.clientY});gesture.current=e.shiftKey?{type:'box',start:p,ids:e.ctrlKey?v.edit.selected:[]}:{type:'pan',start:{x:e.clientX,y:e.clientY},pan:v.pan,moved:false};if(e.shiftKey)setBox({a:p,b:p})}
 useEffect(()=>{const move=(e:PointerEvent)=>{const v=live.current,p=point({x:e.clientX,y:e.clientY}),g=gesture.current,d=portDrag.current;if(v.from)setCursor(p);if(d&&Math.hypot(e.clientX-d.start.x,e.clientY-d.start.y)>4){d.moved=true;setFrom(d.end);setCursor(p)}if(!g)return;if(g.type==='box')setBox({a:g.start,b:p});else if(g.type==='nodes'){if(!g.moved&&Math.hypot(p.x-g.start.x,p.y-g.start.y)*v.scale<3)return;g.moved=true;const offsets=new Map<string,Point>(g.nodes.map((n:any)=>[n.id,{x:n.x+p.x-g.start.x,y:n.y+p.y-g.start.y}]));v.edit.commit({...v.value,nodes:v.value.nodes.map(n=>offsets.has(n.id)?{...n,...offsets.get(n.id)}:n)})}else{if(Math.hypot(e.clientX-g.start.x,e.clientY-g.start.y)>5)g.moved=true;setPan({x:g.pan.x+e.clientX-g.start.x,y:g.pan.y+e.clientY-g.start.y})}}
 const end=(e:PointerEvent)=>{const v=live.current,g=gesture.current,d=portDrag.current;if(d?.moved){const el=document.elementFromPoint(e.clientX,e.clientY)?.closest<HTMLElement>('[data-workflow-port],[data-flow-port]');if(el){const raw=el.dataset.workflowPort||el.dataset.flowPort!,parts=raw.split(':'),other:ConnectionEnd={id:parts[0],direction:parts[1]==='out'?'out':'in',port:kind==='flow'?(parts[1]==='out'?'value':parts.slice(1).join(':')):parts.slice(2).join(':')};finishConnection(d.end,other)}else setFrom(null);skipClick.current=true}portDrag.current=null;if(g?.type==='nodes')v.edit.end();if(g?.type==='pan'&&!g.moved){v.edit.clear();setFrom(null)}if(g?.type==='box'){const p=point({x:e.clientX,y:e.clientY}),sizes=new Map(v.value.nodes.map(n=>{const el=canvas.current?.querySelector<HTMLElement>(`[data-node-id="${n.id}"]`);return[n.id,{width:el?.offsetWidth||300,height:el?.offsetHeight||200}] as const})),ids=marqueeNodeIds(v.value.nodes,g.start,p,sizes);v.edit.setSelected([...new Set<string>([...g.ids,...ids])]);v.edit.setSelectedEdges([])}gesture.current=null;setBox(null)}
 const cancel=()=>{live.current.edit.end();gesture.current=null;portDrag.current=null;setBox(null);setFrom(null)}
 const down=()=>{skipClick.current=false}
 const key=(e:KeyboardEvent)=>{if((e.target as Element)?.closest('input,textarea,select,[contenteditable="true"]'))return;const v=live.current;if(e.key==='Escape'){cancel();return}if(e.key==='Tab'){e.preventDefault();v.toggleLibrary();return}if(v.readOnly&&((e.ctrlKey&&e.key.toLowerCase()!=='c')||e.key==='Delete'))return;if(e.key==='Delete'){e.preventDefault();v.edit.remove();return}if(e.ctrlKey&&!e.altKey){const fn=({c:v.edit.copy,v:v.edit.paste,x:v.edit.cut,z:v.edit.undo,y:v.edit.redo} as Record<string,()=>unknown>)[e.key.toLowerCase()];if(fn){e.preventDefault();fn()}}}
 window.addEventListener('pointerdown',down,true);window.addEventListener('pointermove',move);window.addEventListener('pointerup',end);window.addEventListener('pointercancel',cancel);window.addEventListener('keydown',key);window.addEventListener('blur',cancel);return()=>{window.removeEventListener('pointerdown',down,true);window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',end);window.removeEventListener('pointercancel',cancel);window.removeEventListener('keydown',key);window.removeEventListener('blur',cancel)}},[])
 return{...edit,from,setFrom,cursor,setCursor,box,portEvents,portKey,startNode,selectNode,startCanvas}
}
