import {useState} from 'react'
import {PanelBottomClose,Plus,PencilLine,Check,X,ChevronDown} from 'lucide-react'
import{WorkflowGraph}from'../model/types'
import{poolEntries,newPoolVariable,editPoolVariable}from'../model/variablePool'
import {VariableType} from '../model/workflowValues'
import {executionLabel} from '../services/workflowExecution'
import WorkflowIcon from './WorkflowIcon'
import VariableTypePicker from './VariableTypePicker'
function PoolRow({entry,liveValue,onEdit,disabled}:{entry:ReturnType<typeof poolEntries>[number];liveValue:unknown;onEdit:(patch:{name?:string;type?:VariableType;value?:unknown})=>void;disabled:boolean}){
 const[editing,setEditing]=useState(false),[draft,setDraft]=useState(entry.name),[expanded,setExpanded]=useState(false),[valueDraft,setValueDraft]=useState(''),[error,setError]=useState('')
 const save=()=>{onEdit({name:draft});setEditing(false)}
 return <div className="variable-pool-row"><div className="variable-pool-row-heading"><WorkflowIcon kind="variable" type={entry.type||undefined}/>{editing?<div className="variable-name-editor"><input autoFocus aria-label="变量名称" value={draft} onChange={e=>setDraft(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')save();if(e.key==='Escape')setEditing(false)}}/><button className="icon-button" aria-label="保存变量名称" onClick={save}><Check size={14}/></button><button className="icon-button" aria-label="取消修改变量名称" onClick={()=>setEditing(false)}><X size={14}/></button></div>:<button className="variable-pool-name" disabled={disabled} onClick={()=>{setDraft(entry.name);setEditing(true)}}><span>{entry.name}</span><PencilLine size={13}/></button>}<VariableTypePicker value={entry.type} disabled={disabled} onChange={type=>onEdit({type})}/></div><button className="variable-pool-value" aria-expanded={expanded} title="查看完整值与编辑初始值" onClick={()=>{setExpanded(!expanded);setValueDraft(JSON.stringify(entry.value,null,2)??'null')}}><span>{executionLabel(liveValue,entry.type||undefined)}</span><ChevronDown size={12}/></button>{expanded&&<div className="variable-pool-value-detail"><pre>{typeof liveValue==='string'?liveValue:JSON.stringify(liveValue,null,2)}</pre><label>初始值（JSON）<textarea disabled={disabled||!entry.type} value={valueDraft} onChange={e=>setValueDraft(e.target.value)}/></label><button className="ghost" disabled={disabled||!entry.type} onClick={()=>{try{onEdit({value:JSON.parse(valueDraft)});setError('')}catch(e){setError(e instanceof Error?e.message:String(e))}}}>保存初始值</button>{error&&<p className="danger" role="alert">{error}</p>}</div>}</div>
}
export default function VariablePool({graph,variables,working,open,onClose,onChange,running}:{graph:WorkflowGraph;variables:Record<string,unknown>;working?:Record<string,unknown>;open:boolean;onClose:()=>void;onChange:(graph:WorkflowGraph,variables:Record<string,unknown>)=>void;running:boolean}){
 const[error,setError]=useState(''),[newType,setNewType]=useState<VariableType>('String');const entries=poolEntries(variables)
 const edit=(name:string,patch:{name?:string;type?:VariableType;value?:unknown})=>{try{const result=editPoolVariable(graph,variables,name,patch);onChange(result.graph,result.variables);setError('')}catch(e){setError(e instanceof Error?e.message:String(e))}}
 return <aside className={`variable-pool ${open?'is-open':''}`} inert={!open} aria-hidden={!open}><header className="flow-library-title variable-pool-title"><h3>变量池 {(running||working)&&<small>{running?'实时运行值':'最近运行值'}</small>}</h3><button className="icon-button" aria-label="收起变量池" onClick={onClose}><PanelBottomClose size={18}/></button></header><div className="variable-pool-scroll"><div className="variable-pool-add"><button className="ghost" disabled={running} onClick={()=>{const next=newPoolVariable(variables,newType);onChange(graph,next.variables)}}><Plus size={15}/> 新建变量</button><VariableTypePicker value={newType} disabled={running} onChange={setNewType}/></div>{entries.length?entries.map(entry=>{const raw=working&&Object.hasOwn(working,entry.name)?working[entry.name] as any:undefined,live=raw===undefined?entry.value:raw&&typeof raw==='object'&&'type'in raw&&'value'in raw?raw.value:raw;return <PoolRow key={entry.id} entry={entry} liveValue={live} disabled={running} onEdit={patch=>edit(entry.name,patch)}/>}):<p className="variable-pool-empty">创建变量，再在变量卡片中选择它。</p>}{error&&<p className="danger" role="alert">{error}</p>}</div></aside>
}
