import {WorkflowGraph,uid} from './types'
import {defaultVariable,StoredVariable,strictValue,VariableType,variablePort,variableTypes} from './workflowValues'
export interface PoolEntry {id:string;name:string;type:VariableType|null;value:unknown}
export function poolEntries(variables:Record<string,unknown>):PoolEntry[]{return Object.entries(variables).map(([name,raw])=>{const v=raw as any;const wrapped=v&&typeof v==='object'&&'type'in v&&'value'in v;const value=wrapped?v.value:raw,type=wrapped&&variableTypes.includes(v.type)?v.type:typeof value==='string'?'String':typeof value==='number'?'Number':typeof value==='boolean'?'Boolean':value?.type==='Messages'?'Messages':value?.type==='Image'?'Image':null;return{id:wrapped&&typeof v.id==='string'?v.id:`legacy:${name}`,name,type,value}})}
export function ensureGraphVariables(graph:WorkflowGraph,variables:Record<string,unknown>):Record<string,unknown>{const next={...variables};for(const node of graph.nodes.filter(n=>n.kind==='variable')){if(node.settings.name&&!Object.hasOwn(next,node.settings.name))Object.defineProperty(next,node.settings.name,{value:{id:node.settings.variableId||node.id,type:node.settings.variableType,value:defaultVariable(node.settings.variableType as VariableType)},enumerable:true,writable:true,configurable:true})}return next}
export function newPoolVariable(variables:Record<string,unknown>,type:VariableType='String'){let count=1,name=`${type.toLowerCase()}${count}`;while(Object.hasOwn(variables,name))name=`${type.toLowerCase()}${++count}`;const value:StoredVariable&{id:string}={id:uid(),type,value:defaultVariable(type)};return{variables:{...variables,[name]:value},name,id:value.id}}
export function editPoolVariable(graph:WorkflowGraph,variables:Record<string,unknown>,name:string,patch:{name?:string;type?:VariableType;value?:unknown}){
 const entry=poolEntries(variables).find(v=>v.name===name);if(!entry)throw new Error('变量不存在');const nextName=(patch.name??name).trim();if(!nextName||nextName.length>80)throw new Error('变量名称需要 1–80 个字符');if(nextName!==name&&Object.hasOwn(variables,nextName))throw new Error('变量名称已存在');const type=patch.type||entry.type;if(!type)throw new Error('请先明确变量类型');let value=entry.value;if(Object.hasOwn(patch,'value'))value=strictValue(type,patch.value);else if(patch.type){try{value=strictValue(type,value)}catch{value=defaultVariable(type)}}else value=strictValue(type,value)
 const next={...variables};delete next[name];Object.defineProperty(next,nextName,{value:{id:entry.id,type,value},writable:true,enumerable:true,configurable:true})
 const nodes=graph.nodes.map(n=>['getVariable','setVariable'].includes(n.kind)&&n.settings.name===name?{...n,settings:{...n.settings,name:nextName,variableId:entry.id}}:n.kind==='variable'&&(n.settings.name===name||n.settings.variableId===entry.id)?{...n,settings:{...n.settings,name:nextName,variableId:entry.id,variableType:type,...(patch.type?Object.fromEntries(Object.keys(n.settings).filter(k=>k==='port:value').map(k=>[k,JSON.stringify(value)])): {})},title:`${type} 变量`,inputs:n.inputs.map(p=>p.name==='value'?{...p,type:variablePort(type)}:p),outputs:n.outputs.map(p=>p.name==='value'?{...p,type:variablePort(type)}:p)}:n)
 return{graph:{...graph,nodes},variables:next}
}
export function reconcilePoolMemory(before:Record<string,unknown>,after:Record<string,unknown>,memory:Record<string,Record<string,unknown>>|undefined){if(!memory)return memory;const old=poolEntries(before),current=poolEntries(after);return Object.fromEntries(Object.entries(memory).map(([scope,values])=>{const next={...values};for(const entry of old){const match=current.find(v=>v.id===entry.id);if(!match)continue;if(!Object.hasOwn(next,entry.name))continue;const raw=next[entry.name] as any;let value=raw&&typeof raw==='object'&&'type'in raw&&'value'in raw?raw.value:raw;if(match.type){try{value=strictValue(match.type,value)}catch{value=defaultVariable(match.type)}}delete next[entry.name];Object.defineProperty(next,match.name,{value:{id:match.id,type:match.type,value},enumerable:true,writable:true,configurable:true})}return[scope,next]}))}
